### ISSUE TITLE
[Feat] 홈화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#10]
## ✅ Description

홈 화면 구성 및 화면 전환 기능 구현

## ✔️ TODO
- [x] 홈화면 학교 인증 진행 중 화면 구성
- [x] 홈화면 학교 인증 실패 화면 구성 및 화면 전환 기능 구현
- [x] 홈화면 구성 및 화면 전환 기능 구현
- [x] 학생회 공지 리스트 화면 구성 및 화면 전환 기능 구현
- [x] 저장한 공지 리스트 화면 구성 및 화면 전환 기능 구현
- [x] 놓친 공지사항 화면 구성 및 화면 전환 기능 구현
- [x] 공지사항 세부 화면 구성 및 화면 전환 기능 구현
- [x] 공지사항 작성 화면 구성 및 화면 전환 기능 구현
