### ISSUE TITLE
[Feat] 마이페이지 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#16]
## ✅ Description

마이페이지 화면 구성

## ✔️ TODO
- [x] 마이페이지 메인 화면 구성
- [x] 로그아웃 dialog 구성
- [x] 탈퇴하기 화면 구성
