### ISSUE TITLE
[Feat] 회원가입 API 연동

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#24]
## ✅ Description

회원가입 API 연동 및 화면 디테일 수정

## ✔️ TODO
- [x] 학교 이름 리스트 반환 API 연동
- [x] 학과 이름 리스트 반환 API 연동
- [x] 아이디 중복 확인 API 연동
- [x] 회원가입 API 연동
- [x] FCM 기능 구현
