### ISSUE TITLE
[Feat] 마이페이지 API 연동

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#28]
## ✅ Description

마이페이지 API 연동 및 화면 디테일 수정

## ✔️ TODO
- [x] 사용자 정보 확인 (마이페이지) API 연동
- [x] 로그아웃 API 연동
- [x] 회원탈퇴 API 연동
