### ISSUE TITLE
[Fix] 디자인 QA 반영 및 수정

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#33]
## ✅ Description

디자인 QA 반영 및 수정

## ✔️ TODO
- [x] 제휴업체명 텍스트 디자인 수정
- [x] 공지 리스트 chip 디자인 수정
- [x] FAB elevation 디자인 수정
- [x] dialog 버튼 텍스트 수정
- [x] 커서 텍스트 겹침 오류 수정
