### ISSUE TITLE
[Fix] QA 사항 반영 및 수정 (로직)

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#35]
## ✅ Description

로직 측면에서의 QA 사항 반영 및 수정

## ✔️ TODO
- [x] 놓친 공지사항 배너 로직 수정
- [x] 공지 리스트 카테고리 초기화 오류 수정
- [x] mainActivity onResume 오류 수정
- [x] 공지사항 이미지 1개인 경우 슬라이드 오류 수정
