### ISSUE TITLE
[Feat] amplitude 세팅

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#40]
## ✅ Description

각 이벤트별 amplitude 세팅

## ✔️ TODO
- [x] 회원가입 화면 amplitude 세팅
- [x] 로그인 화면 amplitude 세팅
- [x] 메인 홈 화면 amplitude 세팅
- [x] 놓친 공지사항 화면 amplitude 세팅
- [x] 공지사항 리스트 화면 amplitude 세팅
- [x] 세부 공지사항 화면 amplitude 세팅
- [x] 공지사항 작성 화면 amplitude 세팅
- [x] 제휴업체 화면 amplitude 세팅
- [x] 마이페이지 화면 amplitude 세팅
