### ISSUE TITLE
[Feat] 로그인 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [Studing-Team/Studing-android#5]
## ✅ Description

로그인 화면 구성 및 화면 전환 기능 구현

## ✔️ TODO
- [x] 로그인 화면 구성
- [x] 로그인 화면 전환 기능 구현
- [x] 로그인 오류 dialog 화면 구성
